# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02fee5ebd0c35e7e65f2bdb8944e1ffa"
name = "IG-DevTools"
application_url = "https://shop-test-test.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products, write_files, write_themes, read_metaobjects"

[auth]
redirect_urls = ["https://shop-test-test.vercel.app/instagram/callback"]

[metaobjects.app.instagram_post]
name = "Instagram Post"
access.admin = "merchant_read_write"
access.storefront = "public_read"
capabilities.publishable = false

[metaobjects.app.instagram_post.fields.data]
name = "Data"
type = "json"


[metaobjects.app.instagram_post.fields.image]
name = "Image"
type = "list.file_reference"

[metaobjects.app.instagram_post.fields.caption]
name = "Caption"
type = "multi_line_text_field"

[metaobjects.app.instagram_list]
name = "Instagram List"
access.admin = "merchant_read_write"
access.storefront = "public_read"
capabilities.publishable = false

[metaobjects.app.instagram_list.fields.data]
name = "Data"
type = "json"

[metaobjects.app.instagram_list.fields.posts]
name = "Posts"
type = "list.metaobject_reference<$app:instagram_post>"
